
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_borne:
    resource: "@AppBundle/Controller/BorneController.php"
    type:     annotation

app_carte:
    resource: "@AppBundle/Controller/CarteController.php"
    type:     annotation

app_joueur:
    resource: "@AppBundle/Controller/JoueurController.php"
    type:     annotation

app_couleur:
    resource: "@AppBundle/Controller/CouleurController.php"
    type:     annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation

